backend:
  name: github
  repo: "salah-digital/astro-blog"
  branch: main
  base_url: "https://salah-cms-auth.salahhibrahim131.workers.dev"

media_folder: "public/images"
public_folder: "/images"

locale: 'ar' # تعريب واجهة الإدارة بالكامل

collections:
  - name: "blog"
    label: "المقالات والدراسات"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "عنوان المقال", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "pubDatetime", widget: "datetime"}
      - {label: "الكاتب", name: "author", widget: "string", default: "المستشار صلاح حسن"}
      - {label: "التصنيف (القسم)", name: "tags", widget: "list", default: ["إدارة الأزمات"]}
      - {label: "وصف موجز للمقال", name: "description", widget: "text"}
      - {label: "حفظ كمسودة (إخفاء عن الزوار)", name: "draft", widget: "boolean", default: false}
      - {label: "محتوى المقال والدراسة", name: "body", widget: "markdown"}
